#name of workflow
name: slack workflow

#setting the trigger conditions
on: 
    push:
        branches:
            - 'v[0-9]+.[0-9]+'

        
jobs:
    slack_CI_Success:
        #from this point on it is run in Ubuntu
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              id: checkout_my_source
              uses: actions/checkout@v3

            - name: Run Trivy scanner in fs mode
              id: Trivy_scan
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: '.'
                format: 'table'
                severity: HIGH
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
                
            - name: Build and push
              id: build-and-push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: bryanywr/cicd:${{ github.sha }}
        
            - name: Install Cosign
              id: install_cosign
              uses: sigstore/cosign-installer@v2.2.0
              with:
                cosign-release: 'v2.2.0'

            - name: Check install!
              run: cosign version
            
            - name: Sign image with a key
              run: |
                cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
              env:
                TAGS: bryanywr/cicd:${{ github.sha }}
                COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
                COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
                DIGEST: ${{ steps.build-and-push.outputs.digest }}
      
            
            - name: slack-notification
              id: slack_notification
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_TITLE: "Image build and signed"
                SLACK_MESSAGE: |
                  Name: Bryan Yeo Wei Ren
                  Matriculation: A0287384M
                  Email: e1287867@u.nus.edu
                  GitHub: https://github.com/BryanYWR/CICD.git
                  Docker: https://hub.docker.com/repository/docker/bryanywr/cicd/general
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                